<?php

 /**
  * @SWG\Get(
  *   path="/dpo",
  *   tags={"DPO"},
  *   summary="Get List DPO",
  *   operationId="get data",
  *   @SWG\Parameter(
  *     name="Authorization",
  *     in="header",
  *     description="Authorization Token",
  *     required=true,
  *     type="string"
  *   ),
  *   @SWG\Response(response=200, description="successful operation"),
  *   @SWG\Response(response=406, description="not acceptable"),
  *   @SWG\Response(response=500, description="internal server error")
  * )
  *
  */

  /**
   * @SWG\Get(
   *   path="/dpo/{id}",
   *   tags={"DPO"},
   *   summary="Get DPO by id",
   *   operationId="get data by id",
   *   @SWG\Parameter(
   *     name="Authorization",
   *     in="header",
   *     description="Authorization Token",
   *     required=true,
   *     type="string"
   *   ),
   *   @SWG\Parameter(
   *     name="id",
   *     in="path",
   *     description="get data by id",
   *     required=true,
   *     type="integer"
   *   ),
   *   @SWG\Response(response=200, description="successful operation"),
   *   @SWG\Response(response=406, description="not acceptable"),
   *   @SWG\Response(response=500, description="internal server error")
   * )
   *
   */

   /**
    * @SWG\Post(
    *   path="/dpo",
    *   tags={"DPO"},
    *   summary="Store data DPO",
    *   operationId="Store data",
    *   @SWG\Parameter(
    *     name="Authorization",
    *     in="header",
    *     description="Authorization Token",
    *     required=true,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="nomor_sprint_dpo",
    *     in="formData",
    *     description="nomor_sprint_dpo",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="nama",
    *     in="formData",
    *     description="nama",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamat",
    *     in="formData",
    *     description="alamat",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_jenis_kelamin",
    *     in="formData",
    *     description="kode_jenis_kelamin",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="tempat_lahir",
    *     in="formData",
    *     description="tempat_lahir",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="usia",
    *     in="formData",
    *     description="usia",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_kelompok_usia",
    *     in="formData",
    *     description="kode_kelompok_usia",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_pendidikan_akhir",
    *     in="formData",
    *     description="kode_pendidikan_akhir",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_pekerjaan",
    *     in="formData",
    *     description="kode_pekerjaan",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_warga_negara",
    *     in="formData",
    *     description="kode_warga_negara",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_peran_tersangka",
    *     in="formData",
    *     description="kode_peran_tersangka",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="no_identitas",
    *     in="formData",
    *     description="no_identitas",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_negara",
    *     in="formData",
    *     description="kode_negara",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="kode_jenisidentitas",
    *     in="formData",
    *     description="kode_jenisidentitas",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatktp_idprovinsi",
    *     in="formData",
    *     description="alamatktp_idprovinsi",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatktp_idkabkota",
    *     in="formData",
    *     description="alamatktp_idkabkota",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatktp_kodepos",
    *     in="formData",
    *     description="alamatktp_kodepos",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatdomisili",
    *     in="formData",
    *     description="alamatdomisili",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatdomisili_idprovinsi",
    *     in="formData",
    *     description="alamatdomisili_idprovinsi",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatdomisili_idkabkota",
    *     in="formData",
    *     description="alamatdomisili_idkabkota",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatdomisili_kodepos",
    *     in="formData",
    *     description="alamatdomisili_kodepos",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatlainnya",
    *     in="formData",
    *     description="alamatlainnya",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatlainnya_idprovinsi",
    *     in="formData",
    *     description="alamatlainnya_idprovinsi",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatlainnya_idkabkota",
    *     in="formData",
    *     description="alamatlainnya_idkabkota",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="alamatlainnya_kodepos",
    *     in="formData",
    *     description="alamatlainnya_kodepos",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_warna_rambut",
    *     in="formData",
    *     description="fisik_warna_rambut",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_tipikal_rambut",
    *     in="formData",
    *     description="fisik_tipikal_rambut",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_tinggi_badan",
    *     in="formData",
    *     description="fisik_tinggi_badan",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_perawakan",
    *     in="formData",
    *     description="fisik_perawakan",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_warna_kulit",
    *     in="formData",
    *     description="fisik_warna_kulit",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_bentuk_mata",
    *     in="formData",
    *     description="fisik_bentuk_mata",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_bentuk_wajah",
    *     in="formData",
    *     description="fisik_bentuk_wajah",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_lohat_bahasa",
    *     in="formData",
    *     description="fisik_lohat_bahasa",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="fisik_suku_ras",
    *     in="formData",
    *     description="fisik_suku_ras",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="file_foto_tampak_depan",
    *     in="formData",
    *     description="file_foto_tampak_depan",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="file_foto_tampak_sampingkanan",
    *     in="formData",
    *     description="file_foto_tampak_sampingkanan",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="file_foto_tampak_sampingkiri",
    *     in="formData",
    *     description="file_foto_tampak_sampingkiri",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="file_laporan",
    *     in="formData",
    *     description="file_laporan",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="id_instansi",
    *     in="formData",
    *     description="id_instansi",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="status",
    *     in="formData",
    *     description="status",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Response(response=200, description="successful operation"),
    *   @SWG\Response(response=406, description="not acceptable"),
    *   @SWG\Response(response=500, description="internal server error")
    * )
    *
    */

    /**
      * @SWG\Put(
      *   path="/dpo/{id}",
      *   tags={"DPO"},
      *   summary="update DPO by id",
      *   operationId="update data by id",
      *   @SWG\Parameter(
      *     name="id",
      *     in="path",
      *     description="update data by id",
      *     required=true,
      *     type="integer"
      *   ),
      *   @SWG\Parameter(
      *     name="Authorization",
      *     in="header",
      *     description="Authorization Token",
      *     required=true,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="nomor_sprint_dpo",
      *     in="formData",
      *     description="nomor_sprint_dpo",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="nama",
      *     in="formData",
      *     description="nama",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamat",
      *     in="formData",
      *     description="alamat",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_jenis_kelamin",
      *     in="formData",
      *     description="kode_jenis_kelamin",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="tempat_lahir",
      *     in="formData",
      *     description="tempat_lahir",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="usia",
      *     in="formData",
      *     description="usia",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_kelompok_usia",
      *     in="formData",
      *     description="kode_kelompok_usia",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_pendidikan_akhir",
      *     in="formData",
      *     description="kode_pendidikan_akhir",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_pekerjaan",
      *     in="formData",
      *     description="kode_pekerjaan",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_warga_negara",
      *     in="formData",
      *     description="kode_warga_negara",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_peran_tersangka",
      *     in="formData",
      *     description="kode_peran_tersangka",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="no_identitas",
      *     in="formData",
      *     description="no_identitas",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_negara",
      *     in="formData",
      *     description="kode_negara",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="kode_jenisidentitas",
      *     in="formData",
      *     description="kode_jenisidentitas",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatktp_idprovinsi",
      *     in="formData",
      *     description="alamatktp_idprovinsi",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatktp_idkabkota",
      *     in="formData",
      *     description="alamatktp_idkabkota",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatktp_kodepos",
      *     in="formData",
      *     description="alamatktp_kodepos",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatdomisili",
      *     in="formData",
      *     description="alamatdomisili",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatdomisili_idprovinsi",
      *     in="formData",
      *     description="alamatdomisili_idprovinsi",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatdomisili_idkabkota",
      *     in="formData",
      *     description="alamatdomisili_idkabkota",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatdomisili_kodepos",
      *     in="formData",
      *     description="alamatdomisili_kodepos",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatlainnya",
      *     in="formData",
      *     description="alamatlainnya",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatlainnya_idprovinsi",
      *     in="formData",
      *     description="alamatlainnya_idprovinsi",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatlainnya_idkabkota",
      *     in="formData",
      *     description="alamatlainnya_idkabkota",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="alamatlainnya_kodepos",
      *     in="formData",
      *     description="alamatlainnya_kodepos",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_warna_rambut",
      *     in="formData",
      *     description="fisik_warna_rambut",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_tipikal_rambut",
      *     in="formData",
      *     description="fisik_tipikal_rambut",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_tinggi_badan",
      *     in="formData",
      *     description="fisik_tinggi_badan",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_perawakan",
      *     in="formData",
      *     description="fisik_perawakan",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_warna_kulit",
      *     in="formData",
      *     description="fisik_warna_kulit",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_bentuk_mata",
      *     in="formData",
      *     description="fisik_bentuk_mata",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_bentuk_wajah",
      *     in="formData",
      *     description="fisik_bentuk_wajah",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_lohat_bahasa",
      *     in="formData",
      *     description="fisik_lohat_bahasa",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="fisik_suku_ras",
      *     in="formData",
      *     description="fisik_suku_ras",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="file_foto_tampak_depan",
      *     in="formData",
      *     description="file_foto_tampak_depan",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="file_foto_tampak_sampingkanan",
      *     in="formData",
      *     description="file_foto_tampak_sampingkanan",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="file_foto_tampak_sampingkiri",
      *     in="formData",
      *     description="file_foto_tampak_sampingkiri",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="file_laporan",
      *     in="formData",
      *     description="file_laporan",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="id_instansi",
      *     in="formData",
      *     description="id_instansi",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="status",
      *     in="formData",
      *     description="status",
      *     required=false,
      *     type="string"
      *   ),
      *   @SWG\Response(response=200, description="successful operation"),
      *   @SWG\Response(response=406, description="not acceptable"),
      *   @SWG\Response(response=500, description="internal server error")
      * )
      *
      */

    /**
      * @SWG\Delete(
      *   path="/dpo/{id}",
      *   tags={"DPO"},
      *   summary="Delete DPO by id",
      *   operationId="delete data by id",
      *   @SWG\Parameter(
      *     name="Authorization",
      *     in="header",
      *     description="Authorization Token",
      *     required=true,
      *     type="string"
      *   ),
      *   @SWG\Parameter(
      *     name="id",
      *     in="path",
      *     description="delete data by id",
      *     required=true,
      *     type="integer"
      *   ),
      *   @SWG\Response(response=200, description="successful operation"),
      *   @SWG\Response(response=406, description="not acceptable"),
      *   @SWG\Response(response=500, description="internal server error")
      * )
      *
      */
